import fs from'node:fs';import assert from'node:assert/strict';import{createRequire}from'node:module';const require=createRequire(process.env.CODEX_NODE_MODULES+'/package.json'),{chromium}=require('playwright');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message)});await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;Math.random=()=>.5});
await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>!!window.__mucs,null,{polling:100});const audit=JSON.parse(fs.readFileSync('tests/track2/build-audit.json'));const results=[];
for(const [key,info]of Object.entries(audit)){
 await page.evaluate(k=>window.__mucs.openPractice(k),key);await page.waitForFunction(k=>window.__mucs.getSimApp()?.drawWorld&&document.getElementById('simFrame').contentWindow.document.documentElement.dataset.controls==='pc',key,{timeout:60000,polling:100});
 const frame=page.frames().find(f=>f!==page.mainFrame());
 const result=await frame.evaluate(({appName,key})=>{const a=window[appName],s=a.state,rows=[],service=[];
 for(const name of ['Circuit de Monaco','Suzuka Circuit']){a.resetCar();a.selectCircuit(name);Object.assign(s,{started:true,ignition:true,rivals:[],raceGrid:false,keys:{},realMode:false});a.closeAllDoors(true);a.toggleTestDriver(true);let i=0;for(;i<120*600;i++){a.updatePhysics(1/120);s.time+=1/120;if(![s.distanceM,s.speedMps,s.laneOffset,s.headingRel].every(Number.isFinite))throw Error(key+' nonfinite');if(s.distanceM>s.route.totalM+15)break;}rows.push({name,complete:s.distanceM>s.route.totalM,d:s.distanceM,time:i/120,events:a.contactInfo().events.length});}
 for(const real of[false,true]){a.resetCar();a.selectCircuit('Silverstone Circuit');const p=a.pitModel();Object.assign(s,{started:true,ignition:true,realMode:real,testDriver:false,assist:false,keys:{},rivals:[],raceGrid:false,inPitLane:true,pitStage:'transit',pitQ:a.pitBox(a.TEAM.slot),pitBase:p.entry,laneOffset:3.1,speedMps:0,damage:.6,pitFuelAdd:0});s.distanceM=p.entry+s.pitQ/p.length*p.span;for(const k of Object.keys(s.sys))s.sys[k]=.4;const before={...s.sys};for(let i=0;i<120*100&&s.pitStage!=='exit';i++){a.updatePhysics(1/120);s.time+=1/120;}service.push({real,stage:s.pitStage,stops:s.pitStops,damage:s.damage,before,after:{...s.sys},fuel:s.fuelKg});}
 return{key,rows,service};},{appName:info.app,key});results.push(result);console.log(JSON.stringify(result));fs.writeFileSync('tests/track2/driving-results.json',JSON.stringify({results,errors},null,2));await page.evaluate(()=>window.__mucs.backToGarage());
}
await browser.close();assert.equal(errors.length,0);assert.ok(results.every(r=>r.rows.every(l=>l.complete)),'complete laps');assert.ok(results.every(r=>r.service.every(s=>s.stage==='exit'&&s.stops===1)),'pit service');
