import fs from'node:fs';import assert from'node:assert/strict';import{createRequire}from'node:module';import{pathToFileURL}from'node:url';const require=createRequire(process.env.CODEX_NODE_MODULES+'/package.json'),{chromium}=require('playwright');const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>!!window.__mucs);await page.screenshot({path:'tests/track2/garage.png'});
const load=async(key)=>{await page.evaluate(k=>window.__mucs.openPractice(k),key);await page.waitForFunction(()=>window.__mucs.getSimApp()?.drawWorld&&document.querySelector('#simFrame').contentDocument.documentElement.dataset.controls,null,{polling:100,timeout:60000});const f=page.frames().find(f=>f!==page.mainFrame());await f.getByRole('button',{name:'Press to Start',exact:true}).click();return f;};
for(const version of['1','2']){await page.selectOption('#trackVersion',version);await page.selectOption('#controlMode','dpad');await page.setViewportSize({width:1100,height:650});const f=await load('bugatti');assert.equal(await page.evaluate(()=>window.__mucs.activeTrackVersion),version);
 await f.evaluate(()=>{const a=BugattiApp;a.setView('drive');a.setGear('G',1);a.state.assist=false;a.state.testDriver=false;});
 assert.ok(await f.locator('.mobile-pad').isVisible());assert.ok(await f.locator('.touch-wheel').isVisible());const leftBox=await f.locator('[data-pad="left"]').boundingBox(),upBox=await f.locator('[data-pad="up"]').boundingBox(),cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:leftBox.x+20,y:leftBox.y+20,id:1},{x:upBox.x+20,y:upBox.y+20,id:2}]});
 const held=await f.evaluate(()=>({left:BugattiApp.state.keys.ArrowLeft,up:BugattiApp.state.keys.ArrowUp}));assert.ok(held.left&&held.up);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await cdp.detach();assert.ok(await f.evaluate(()=>!BugattiApp.state.keys.ArrowLeft&&!BugattiApp.state.keys.ArrowUp));
 await page.screenshot({path:'tests/track2/dpad-'+version+'.png'});await page.evaluate(()=>window.__mucs.backToGarage());await page.selectOption('#controlMode','pc');await page.setViewportSize({width:430,height:900});const pc=await load('bugatti');assert.ok(!await pc.locator('.mobile-pad').isVisible());assert.ok(!await pc.locator('.touch-wheel').isVisible());await page.evaluate(()=>window.__mucs.backToGarage());results.push({version,landscapeDpad:true,retainedWheel:true,multiTouch:true,portraitPC:true});}
await page.setViewportSize({width:1440,height:900});await page.selectOption('#trackVersion','2');await load('db5');assert.equal(await page.evaluate(()=>window.__mucs.activeTrackVersion),'1');await page.evaluate(()=>window.__mucs.backToGarage());await load('f1mercedes');const f=page.frames().find(f=>f!==page.mainFrame());await f.evaluate(()=>{const a=MercedesF1App;a.setView('drive');a.selectCircuit('Suzuka Circuit');a.state.distanceM=4900;a.state.speedMps=0;a.drawWorld();});await page.screenshot({path:'tests/track2/mercedes-suzuka.png'});
await page.evaluate(()=>{window.__mucs.applyCfg({type:'cfg',hostId:'fixture-host',trackVersion:'1',track:'Silverstone Circuit',phase:'lobby'},'fixture-peer');});await page.waitForFunction(()=>window.__mucs.getSimApp()?.state.route.name==='Silverstone Circuit'&&window.__mucs.activeTrackVersion==='1',null,{timeout:60000});assert.ok(await page.evaluate(()=>!window.__mucs.getSimApp().trackModel));
await page.close();
const offline=await browser.newPage({viewport:{width:1200,height:800}});offline.on('pageerror',e=>errors.push(e.message));const network=[];await offline.route('**/*',route=>{const u=route.request().url();if(/^https?:/.test(u)){network.push(u);return route.abort();}return route.continue();});await offline.goto(pathToFileURL(process.cwd()+'/index-offline.html').href,{waitUntil:'domcontentloaded',timeout:120000});await offline.waitForFunction(()=>!!window.__mucs);for(const version of['2','1']){await offline.selectOption('#trackVersion',version);await offline.evaluate(()=>window.__mucs.openPractice('bugatti'));await offline.waitForFunction(()=>window.__mucs.getSimApp()?.drawWorld&&document.querySelector('#simFrame').contentDocument.documentElement.dataset.controls,null,{timeout:60000,polling:100});assert.equal(await offline.evaluate(()=>window.__mucs.activeTrackVersion),version);const of=offline.frames().find(f=>f!==offline.mainFrame());await of.evaluate(()=>{const a=BugattiApp;a.selectCircuit('Suzuka Circuit');a.setView('drive');a.state.started=true;a.drawWorld();});await offline.evaluate(()=>window.__mucs.backToGarage());}results.push({offlineVersions:true,excludedRetained:true,hostVersionSync:true});await browser.close();fs.writeFileSync('tests/track2/settings-results.json',JSON.stringify({results,errors},null,2));assert.equal(errors.length,0);console.log(results);
