import fs from'node:fs';import assert from'node:assert/strict';import{createRequire}from'node:module';const require=createRequire(process.env.CODEX_NODE_MODULES+'/package.json'),{chromium}=require('playwright');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message)});await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;Math.random=()=>.5});
await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>!!window.__mucs,null,{polling:100});const audit=JSON.parse(fs.readFileSync('tests/track2/build-audit.json'));const results=[];
for(const [key,info]of Object.entries(audit)){
 await page.evaluate(k=>window.__mucs.openPractice(k),key);await page.waitForFunction(k=>window.__mucs.getSimApp()?.drawWorld&&document.getElementById('simFrame').contentWindow.document.documentElement.dataset.controls==='pc',key,{timeout:60000,polling:100});
 const frame=page.frames().find(f=>f!==page.mainFrame());
 const result=await frame.evaluate(({appName,key})=>{const a=window[appName],s=a.state,rows=[];a.setView('drive');s.started=s.ignition=true;for(const name of Object.keys(a.trackData)){a.resetCar();a.selectCircuit(name);s.started=s.ignition=true;s.rivals=[];s.raceGrid=false;s.assist=false;s.testDriver=false;s.keys.ArrowUp=true;a.setGear('G',1);for(let i=0;i<360;i++){a.updatePhysics(1/120);s.time+=1/120;}if(![s.speedMps,s.distanceM,s.laneOffset,s.headingRel,s.rpm].every(Number.isFinite))throw Error(key+' nonfinite '+name);a.updateUi();a.drawWorld();rows.push({name,d:s.distanceM,speed:s.speedMps});}const brand=Object.keys(a.CIRCUITS).filter(n=>!a.trackData[n]);for(const n of brand){a.selectCircuit(n);a.updatePhysics(1/120);a.drawWorld();if(a.trackModel())throw Error('Brand replaced');}return{key,rows,brand,controls:document.documentElement.dataset.controls};},{appName:info.app,key});results.push(result);console.log('PASS',key);if(['bugatti','f1mercedes','f1redbull','solusgt'].includes(key))await page.screenshot({path:'tests/track2/'+key+'.png'});await page.evaluate(()=>window.__mucs.backToGarage());
}
fs.writeFileSync('tests/track2/smoke-results.json',JSON.stringify({results,errors},null,2));await browser.close();assert.equal(errors.length,0);assert.equal(results.length,56);
